#!/usr/bin/env python3

"""Generate Bullet Physics API wrapper for PXC.

This script orchestrates the API generation process:
1. Uses CastXML to extract C++ API information to XML
2. Generates PXC wrapper code from the XML
"""

from __future__ import annotations

import sys
import re
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parent /
  '/usr/local/share/pxclib/script'))
from castxml_generate_xml import CastXMLGenerate
from generate_px_wrapper import GeneratePxWrapper

def main() -> int:
    """Main entry point for Bullet API generation."""
    try:
        # Change to script directory
        script_dir = Path(__file__).resolve().parent
        import os
        os.chdir(script_dir)
        
        print("Step 1: Generating XML from Bullet headers using CastXML...")
        xml_generator = CastXMLGenerate(
            include_path=Path("../../../bullet/src").resolve(),
            filter_regex=re.compile(
              r"(BulletCollision|btBullet|BulletDynamics|LinearMath)"
            ),
            exclude_regex=re.compile(
                r"(autogenerated/bullet.h"
                "|btConvexHull.h"
                "|vectormath"
                "|XmlWorldImporter"
                "|BulletSoftBody"
                "|Gimpact"
                "|Featherstone"
                "|MLCPSolvers"
                "|Vehicle"
                "|Bullet3Collision"
                "|Bullet3Common"
                "|Bullet3Dynamics"
                "|Bullet3Geometry"
                "|Bullet3OpenCL"
                "|Bullet3Serialize)"
            ),
            castxml_command = [
                "castxml",
                "--castxml-gccxml",
                "--castxml-cc-gnu",
                "g++-11",
                "-std=c++17",
            ],
        )
        xml_generator.generate()
        print("  ✓ XML generation complete")
        
        print("\nStep 2: Generating PXC wrapper from XML...")
        wrapper_generator = GeneratePxWrapper(
            xml_filename="castxml.xml",
            px_filename="api.px",
            px_namespace="bullet_physics::api",
            filter_path_regex=re.compile(
                r"/build/bullet/"
            ),
            filter_export_regex=re.compile(
                r"(^bt|^Bvh|^Quantized|^PHY_|^IndexedMeshArray|^size_type)"
            ),
            filter_extern_regex=re.compile(
                r'(?!)'
            ),
            types_mt={
                "btVector3": "pure tsvaluetype",
                "btMatrix3x3": "pure tsvaluetype",
                "btTransform": "pure tsvaluetype",
            },
            px_header=(
                "public namespace bullet_physics::api \"export-unsafe\";\n"
                "public import core::common -;\n"
                "public import core::container::raw -;\n"
                "public import core::pointer::raw -;\n"
                "public import core::meta m;\n"
                "public import core::meta::vararg va;\n"
                "public import bullet_physics::base -;\n"
            ),
            primitive_typemap={
                "int": "int",
                "unsigned int": "uint",
                "long int": "long",
                "long unsigned int": "ulong",
                "long long int": "longlong",
                "long long unsigned int": "ulonglong",
                "short int": "short",
                "short unsigned int": "ushort",
                "char": "char",
                "unsigned char": "uchar",
                "float": "float",
                "double": "double",
                "void": "void",
                "bool": "bool",
                "size_t": "size_t",
                "uint32_t": "uint32_t",
                "uint64_t": "uint64_t",
                "string": "std_string",
                "shared_ptr": "std_shared_ptr",
                "vector": "std_vector",
                "btScalar": "btScalar",
            }
        )
        wrapper_generator.run()
        print("  ✓ PXC wrapper generation complete")
        
        print("\n✓ Bullet API generation completed successfully!")
        return 0
        
    except Exception as ex:
        print(f"\n✗ Error during API generation: {ex}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        return 1

if __name__ == "__main__":
    sys.exit(main())
